example/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.user_list, name='user_list'),
    url(r'^login/$',views.log_in, name='log_in'),
    url(r'^logout/$',views.log_out, name='log_out'),
    url(r'^sign-up/$',views.sign_up, name='sign_up'),
]

example_channel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('example.urls', namespace="example")),
]

example/models.py
from django.conf import settings
from django.db import models


class LoggedInUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='logged_in_user')

example/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import logout, login, get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

User = get_user_model()
print(User)


@login_required()
def user_list(request):
    users = User.objects.select_related('logged_in_user')
    for user in users:
        user.status = 'Online' if hasattr(user, 'logged_in_user') else 'Offline'

    return render(request, 'user_list.html')


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('example:user_list'))
        else:
            print(form.errors)
    return render(request, 'log_in.html', locals())


def log_out(request):
    logout(request)
    return redirect(reverse('example:user_list'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('example:log_in'))
        else:
            print(form.errors)
    return render(request, 'sign_up.html', locals())

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <title>Example Channels</title></head>
{% block styles %}

{% endblock %}
<body>
<div class="container" style="border: 2px solid #eeeeee"><br> {% block content %}{% endblock content %} </div>
<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="/static/bootstrap.min.js"></script>
{% block script %}{% endblock script %} </body>
</html>

templates/log_in.html
{%  extends 'base.html' %}
{% block content %}
    <form action="{%  url 'example:log_in' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
                {{ form.errors }}
        <button type="submit">log in</button>
    </form>
    <p>Don't have an account? <a href="{% url 'example:sign_up' %}">Sign up!</a></p>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'example:sign_up' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
            {{ form.errors }}
        {% endfor %}
        <button type="submit">Sign up</button>
     <p>Already have an account? <a href="{% url 'example:log_in' %}">Log in!</a></p>
    </form>
{% endblock content %}

templates/user_list.html
{% extends 'base.html' %}
{% block styles %}
    <style>
        #channel_message {
            height: 500px;
            width: 1000px;
            border: 1px solid #e1e1e1;
            margin-left: 80px;
            margin-bottom: 10px;
            overflow: auto;
            padding: 10px;
        }
    </style>
{% endblock %}
{% block content %}

    <div class="row" id="channel_message"></div>
    <div class="row">
        <div class="col-lg-8" style="margin-left: 210px ">
            <span style="display: none;" id="uname">{{ request.user }}</span>
            <textarea class="form-control " id="msg" cols="10" rows="5" placeholder="请输入发送内容">
            </textarea>
            <button class="btn btn-primary " style="float: right" onclick="SendMsg()"> 发送</button>
        </div>

    </div>
{% endblock %}
{% block script %}
    <script>
        var current_user = $('#uname').text();
        var socket = new WebSocket("ws://" + window.location.host + '/user/');
        socket.onopen = function open() {
            console.log("WebSocket connected");
        };
        socket.onmessage = function (message) {
            var data = JSON.parse(message.data);
            var myDate = new Date();
            var time = myDate.toLocaleTimeString();
            var msg_div = document.createElement('div');
            msg_div.innerHTML = (time + '     ' + data['user'] + ' : ' + data['text']);
            var button = document.createElement("button");
            button.setAttribute('class', 'close');
            button.setAttribute('type', 'button');
            button.setAttribute('data-dismiss', 'alert');
            button.innerHTML = '&times;';
            if (data['message']) {
                if (data['user'] == current_user) {
                    msg_div.append(button);
                    msg_div.setAttribute('class', 'alert alert-warning');
                    $('#channel_message').append(msg_div);
                }
                else {
                    msg_div.append(button);
                    msg_div.setAttribute('class', 'alert alert-success');
                    $('#channel_message').append(msg_div);
                }
                var before_height = $("#channel_message").scrollTop();
                $("#channel_message").scrollTop(before_height+100);
            }
        };
        if (socket.readyState == WebSocket.OPEN) {
            socket.onopen();
        }

        function SendMsg() {
            var msg = $('#msg').val();
            socket.send(msg);
            $('#msg').val('');

        }
    </script>
{% endblock %}